# Generated by Django 5.1.5 on 2025-02-09 14:53

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='click',
        ),
        migrations.RemoveField(
            model_name='shortenedurl',
            name='user',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_link',
            field=models.CharField(default=shortener.models.generate_short_link, max_length=10, unique=True),
        ),
    ]
