# Generated by Django 5.1.5 on 2025-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenedurl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='clicks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
